"""add approvals table

Revision ID: 354633be6c21
Revises: ec55310ae9a0
Create Date: 2026-01-28 11:50:11.554396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354633be6c21'
down_revision = 'ec55310ae9a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('original_task', sa.Text(), nullable=True),
    sa.Column('modified_task', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('calendar_event_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('calendar_event_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.drop_table('approvals')
    # ### end Alembic commands ###
